# name: Check Symlinks and Folder Changes

# on:
#   pull_request:
#     paths:
#       - '**' # Trigger on any file change

# jobs:
#   check_symlinks_and_folders:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: List changed files
#       id: list_changes
#       run: |
#         git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
    
#     - name: Debug changed files
#       run: cat changed_files.txt

#     - name: Check for symlink changes
#       id: symlink_changes
#       run: |
#         grep -E '^(A|M) .* -> ' changed_files.txt > symlink_changes.txt
#         if [ -s symlink_changes.txt ]; then
#           echo "Symlink changes detected:"
#           cat symlink_changes.txt
#           exit 1
#         else
#           echo "No symlink changes detected."
#         fi

#     - name: Check for changes in symlink-containing folders
#       id: folder_changes
#       run: |
#         changed_folders=$(grep -E '^(A|M) .* -> ' changed_files.txt | awk -F/ '{print $1}' | sort -u)
#         for folder in $changed_folders; do
#           if [ -L "$folder" ]; then
#             echo "Symlink added in folder $folder. Disallowing merge of files from this folder."
#             exit 1
#           fi
#         done

name: Symlink Check

on:
  pull_request:
    paths:
      - '**'

jobs:
  check_symlinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch main branch from remote
        run: git fetch origin main:main

      - name: Find symlinks in folders
        run: |
          find . -type l -exec dirname {} + | sort -u | sed 's|^./||' > symlink_folders.txt
          cat symlink_folders.txt
     
      # - name: Display changed files
      #   run: |
      #       git diff --name-only origin/main | xargs dirname | sort -u > changed_directories.txt
      #       cat changed_directories.txt
      - name: Display changed files
        run: |
          # List all added and modified files
          git diff --name-status origin/main > changed_files.txt
        
          # Extract directory paths of added and modified files
          grep -E "^[AM]\s" changed_files.txt | awk '{print $2}' | xargs dirname | sort -u > added_modified_directories.txt
        
          # List all deleted files
          grep -E "^D\s" changed_files.txt | awk '{print $2}' > deleted_files.txt
        
          # Extract directory paths of deleted files and append them to added_modified_directories.txt
          cat deleted_files.txt | xargs dirname >> added_modified_directories.txt
        
          # Filter out symlink directories from the list of added and modified directories
          grep -v -f <(find . -type l) added_modified_directories.txt | sort -u > changed_directories.txt
        
          # Cleanup temporary files
          rm changed_files.txt added_modified_directories.txt deleted_files.txt
          cat changed_directories.txt

      
      - name: Check for new files in symlink folders
        run: |
          while IFS= read -r changed_dir; do
            # Check if the changed directory matches any symlink-containing folder
            if grep -q "^$changed_dir\$" symlink_folders.txt; then
              echo "Error: New files added to symlink folder $changed_dir"
              exit 1
            fi
          done < changed_directories.txt

      - name: Cleanup
        run: rm symlink_folders.txt
