# name: Check Symlinks and Folder Changes

# on:
#   pull_request:
#     paths:
#       - '**' # Trigger on any file change

# jobs:
#   check_symlinks_and_folders:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: List changed files
#       id: list_changes
#       run: |
#         git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
    
#     - name: Debug changed files
#       run: cat changed_files.txt

#     - name: Check for symlink changes
#       id: symlink_changes
#       run: |
#         grep -E '^(A|M) .* -> ' changed_files.txt > symlink_changes.txt
#         if [ -s symlink_changes.txt ]; then
#           echo "Symlink changes detected:"
#           cat symlink_changes.txt
#           exit 1
#         else
#           echo "No symlink changes detected."
#         fi

#     - name: Check for changes in symlink-containing folders
#       id: folder_changes
#       run: |
#         changed_folders=$(grep -E '^(A|M) .* -> ' changed_files.txt | awk -F/ '{print $1}' | sort -u)
#         for folder in $changed_folders; do
#           if [ -L "$folder" ]; then
#             echo "Symlink added in folder $folder. Disallowing merge of files from this folder."
#             exit 1
#           fi
#         done

name: Symlink Check

on:
  pull_request:
    paths:
      - '**'

jobs:
  check_symlinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch main branch from remote
        run: git fetch origin main:main

      - name: Find symlinks in folders
        run: |
          find . -type l -exec dirname {} + | sort -u > symlink_folders.txt
          cat symlink_folders.txt

      - name: Check for new files in symlink folders
        run: |
          # while IFS= read -r folder; do
          #   if [ -n "$(git diff --name-only main $folder)" ]; then
          #     echo "Error: New files added to symlink folder $folder"
          #     exit 1
          #   fi
          # done < symlink_folders.txt

          # while IFS= read -r folder; do
          #   if [ -d "$folder" ]; then
          #     if [ -n "$(git diff --name-only origin/main $folder)" ]; then
          #       echo "Error: New files added to symlink folder $folder"
          #       exit 1
          #     fi
          #   fi
          # done < symlink_folders.txt

          while IFS= read -r symlink_folder; do
            echo "folder1: $symlink_folder"
            # Check if the folder exists and is not the root directory
            if [ -d "$symlink_folder" ] && [ "$symlink_folder" != "." ]; then
              echo "folder2: $symlink_folder"
              # Check if any changed files have the exact same path as the symlink-containing folder
              if [ -n "$(git diff --name-only origin/main | grep "^$symlink_folder\$")" ]; then
                echo "folder3: $symlink_folder"
                echo "Error: New files added to symlink folder $symlink_folder"
                exit 1
              fi
            fi
          done < symlink_folders.txt

      - name: Cleanup
        run: rm symlink_folders.txt
