name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  repository_dispatch:
    types: [file-changed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Read and fetch data from symlinks
        run: |
          SYMLINKS=$(find . -type l)
          for SYMLINK_PATH in $SYMLINKS; do
            echo "symlink path $SYMLINK_PATH"
            URL=$(readlink $SYMLINK_PATH)
            URL=${URL/github.com/raw.githubusercontent.com}
            URL=${URL/blob\//}
            FetchedContent=$(curl -s -H "Authorization: token ${{ secrets.TEST_TOKEN }}" $URL)
            echo "fetched content: $FetchedContent"
            rm $SYMLINK_PATH
            echo "$FetchedContent" > $SYMLINK_PATH
          done

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
